version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: salimalsazu
      POSTGRES_DB: erp
    volumes:
      - type: bind
        source: /root/volumes/erp/db
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my-network

  server:
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    container_name: server-container
    depends_on:
      - postgres
    ports:
      - 7000:7000
    volumes:
      - type: bind
        source: /root/volumes/erp/data
        target: /app/uploads
    networks:
      - my-network

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    container_name: client-container
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`account.24-7sourcingbd.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.services.client.loadbalancer.server.port=3000" # Internal port
      - "traefik.http.routers.client.tls.certresolver=myresolver" # Use Let's Encrypt
    restart: unless-stopped
    networks:
      - my-network

  backup-service:
    build:
      context: ./backup-service
    container_name: backup-service
    volumes:
      - type: bind
        source: /var/backups
        target: /backup
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - my-network

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable the Traefik dashboard (remove in production)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=salim@24-7sourcingbd.com" # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Docker socket to read container labels
      - "./letsencrypt:/letsencrypt" # Persist SSL certificates
    restart: unless-stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
