export enum tagTypes {
  user = "user",
  item = "item",
  stationaryList = "stationaryList",
  asset = "asset",
  assign = "assign",
  fuel = "fuel",
  vehicle = "vehicle",
  doc = "doc",
  mobileBill = "mobileBill",
  requisition = "requisition",
  account = "account",
  transaction = "transaction",
  salary = "salary",
  group = "group",
  subGroup = "subGroup",
  dashboard = "dashboard",
  log = "log",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.item,
  tagTypes.stationaryList,
  tagTypes.asset,
  tagTypes.assign,
  tagTypes.fuel,
  tagTypes.vehicle,
  tagTypes.doc,
  tagTypes.mobileBill,
  tagTypes.requisition,
  tagTypes.account,
  tagTypes.transaction,
  tagTypes.salary,
  tagTypes.group,
  tagTypes.subGroup,
  tagTypes.dashboard,
  tagTypes.log,
];
