import { z } from 'zod';

// Enum for SalaryMonth
const SalaryMonth = z.enum([
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]);

// Zod validation schema for Salary
const createSalary = z.object({
  salaryId: z.string().uuid().optional(), // Generated by default, so it's optional in the schema
  salaryMonth: SalaryMonth,
  salaryYear: z.string().length(4, "Year must be 4 digits long"),
  userId: z.string(),
  basicSalary: z.number().min(0),
  houseRent: z.number().min(0),
  medicalAllowance: z.number().min(0),
  conveyance: z.number().min(0),
  otherAllowance: z.number().min(0),
  totalSalary: z.number().min(0),
  absentDeduction: z.number().min(0),
  advanceSalaryDeduction: z.number().min(0),
  mealAndMobileBillDeduction: z.number().min(0),
  netPayableSalary: z.number().min(0),
  tdsOnSalary: z.number().min(0),
  netSalary: z.number().min(0),
});

export default createSalary;
